const listJson=[
  {
    fileType:"gw",
    params:{
      showTotal:true,
      fileType:"gw"
    },
    url:"fn/mobileToDoAndRead/getToDoAndReadList2"
  },
  {
    fileType:"ToOversee",
    params:{
      showTotal:true,
      fileType:"ToOversee"
    },
    url:"fn/mobileToDoAndRead/getToDoAndReadList2"
  },
  {
    fileType:"ToRead",
    params:{
      showTotal:true,
      fileType:"ToRead"
    },
    url:"fn/mobileToDoAndRead/getToDoAndReadList2"
  },
  {
    fileType:"hy",
    params:{},
    url:"fn/MeetingMobile/meetingTodo"
  },
  {
    fileType:"cuofa",
    params:{},
    url:"fn/flow/mobileRecyclingListData"
  },
  {
    fileType:"weidaka",
    params:{
    },
    url:"fn/epidemic/unClockInList"
  },
  {
    fileType:"zhcx",
    params:{
    },
    url:"fn/personalcenter/mobileQueryData?sourceType=19"
  },
]
export default listJson