import { StyleProp, TextStyle } from 'react-native'

export const ds_font0: StyleProp<TextStyle>
export const ds_font1: StyleProp<TextStyle>
export const ds_font2: StyleProp<TextStyle>
export const ds_font3: StyleProp<TextStyle>
export const ds_font3_m: StyleProp<TextStyle>
export const ds_font4: StyleProp<TextStyle>
export const ds_font4_m: StyleProp<TextStyle>
export const ds_font5: StyleProp<TextStyle>
export const ds_font6: StyleProp<TextStyle>
export const ds_font7: StyleProp<TextStyle>
export const mast-input: StyleProp<TextStyle>
export const hello: StyleProp<TextStyle>
export const fn: StyleProp<TextStyle>
export const ellipsis: StyleProp<TextStyle>
export const point: StyleProp<TextStyle>
export const ds-announcement: StyleProp<TextStyle>
export const announcement-header: StyleProp<TextStyle>
export const van-icon: StyleProp<TextStyle>
export const van-nav-bar__title: StyleProp<TextStyle>
export const announcement-search: StyleProp<TextStyle>
export const van-search: StyleProp<TextStyle>
export const van-search__content: StyleProp<TextStyle>
export const announcement-list: StyleProp<TextStyle>
export const announcement-list-inner: StyleProp<TextStyle>
export const announcement-list-content: StyleProp<TextStyle>
export const announcement-list-content-tit: StyleProp<TextStyle>
export const announcement-list-time: StyleProp<TextStyle>
export const announcement-list-time-left: StyleProp<TextStyle>
export const announcement-list-time-right: StyleProp<TextStyle>
export const announcement-list-content:last-child: StyleProp<TextStyle>
export const ds-announceDetail: StyleProp<TextStyle>
export const announceDetail-tab: StyleProp<TextStyle>
export const van-tabvan-tab--active: StyleProp<TextStyle>
export const van-tabs__line: StyleProp<TextStyle>
export const van-tab: StyleProp<TextStyle>
export const van-tabs__content: StyleProp<TextStyle>
export const van-tab__pane: StyleProp<TextStyle>
export const announceDetail-tab-content: StyleProp<TextStyle>
export const announceDetail-tab-content-tit: StyleProp<TextStyle>
export const announceDetail-tab-content-datail: StyleProp<TextStyle>
export const announceDetail-tabbar: StyleProp<TextStyle>
export const announceDetail-tabbar-right: StyleProp<TextStyle>
export const dsf-select-person: StyleProp<TextStyle>
export const footer: StyleProp<TextStyle>
export const num: StyleProp<TextStyle>
export const reset: StyleProp<TextStyle>
export const choose: StyleProp<TextStyle>
export const _add_tree: StyleProp<TextStyle>
export const checkbox: StyleProp<TextStyle>
export const van-icon: StyleProp<TextStyle>
export const van-icon-success::before: StyleProp<TextStyle>
