import { StyleProp, TextStyle } from 'react-native'

export const week-slider: StyleProp<TextStyle>
export const slider-title: StyleProp<TextStyle>
export const title-icon-active: StyleProp<TextStyle>
export const title-icon-unactive: StyleProp<TextStyle>
export const slider-content: StyleProp<TextStyle>
export const date-box: StyleProp<TextStyle>
export const lang-box: StyleProp<TextStyle>
export const day-of-week: StyleProp<TextStyle>
export const day-title: StyleProp<TextStyle>
export const day-date: StyleProp<TextStyle>
export const day-dot: StyleProp<TextStyle>
export const ds_funList: StyleProp<TextStyle>
export const marginBottom: StyleProp<TextStyle>
export const van-pull-refresh__track: StyleProp<TextStyle>
export const list_wrap: StyleProp<TextStyle>
export const fontcolor: StyleProp<TextStyle>
export const item_box: StyleProp<TextStyle>
export const item: StyleProp<TextStyle>
export const homeworklist_item: StyleProp<TextStyle>
export const item_content: StyleProp<TextStyle>
export const teacheval_itemContent: StyleProp<TextStyle>
export const time: StyleProp<TextStyle>
export const state: StyleProp<TextStyle>
export const title: StyleProp<TextStyle>
export const info_box: StyleProp<TextStyle>
export const item_btn_area: StyleProp<TextStyle>
export const vacate_item_btn_area: StyleProp<TextStyle>
export const homework_item_btn_area: StyleProp<TextStyle>
export const item_btn: StyleProp<TextStyle>
export const single_word: StyleProp<TextStyle>
export const item-text-only: StyleProp<TextStyle>
export const left_day: StyleProp<TextStyle>
export const homewrok_leftday: StyleProp<TextStyle>
export const firstItem: StyleProp<TextStyle>
export const lastItem: StyleProp<TextStyle>
