import { StyleProp, TextStyle } from 'react-native'

export const van-button--theme: StyleProp<TextStyle>
export const van-button--theme_main: StyleProp<TextStyle>
export const van-tabs__line: StyleProp<TextStyle>
export const van-tab: StyleProp<TextStyle>
export const van-tabvan-tab--active: StyleProp<TextStyle>
export const van-swipe: StyleProp<TextStyle>
export const van-tabbar-item__icon: StyleProp<TextStyle>
export const van-tabbar-item: StyleProp<TextStyle>
export const iconfont: StyleProp<TextStyle>
export const van-tabbar-item--active: StyleProp<TextStyle>
export const bar: StyleProp<TextStyle>
export const peg: StyleProp<TextStyle>
export const spinner-icon: StyleProp<TextStyle>
export const dsf-treeselect-sidepopup: StyleProp<TextStyle>
export const van-tree-select__item: StyleProp<TextStyle>
export const van-tree-select__item--active: StyleProp<TextStyle>
export const van-sidebar-item--select: StyleProp<TextStyle>
export const signCustom: StyleProp<TextStyle>
export const van-button--large: StyleProp<TextStyle>
export const van-dialog__confirm,van-dialog__confirm:active: StyleProp<TextStyle>
export const exashade: StyleProp<TextStyle>
export const van-dialog__message: StyleProp<TextStyle>
export const van-dialog__confirm:active: StyleProp<TextStyle>
export const van-dialog__footer: StyleProp<TextStyle>
export const van-dialog__confirm: StyleProp<TextStyle>
export const van-toast: StyleProp<TextStyle>
export const van-icon: StyleProp<TextStyle>
export const van-search: StyleProp<TextStyle>
export const van-cell: StyleProp<TextStyle>
export const van-field: StyleProp<TextStyle>
export const van-button--primary: StyleProp<TextStyle>
export const van-button--default: StyleProp<TextStyle>
